DROP FUNCTION obtener_reporte_evaluacionoftalmologica(integer);

CREATE OR REPLACE FUNCTION obtener_reporte_evaluacionoftalmologica(IN p_norden integer)
  RETURNS TABLE(nombre text, apellido text, edad text, n_orden integer, dni integer, fecha_nac date, empresa text, contrata text, nom_examen text, sexo "char", cod_of integer, fecha_of date, rbecptosisod boolean, rbecptosisoi boolean, rbecestrabismood boolean, rbecestrabismooi boolean, rbecconjuntivitisod boolean, rbecconjuntivitisoi boolean, rbeccataratasod boolean, rbeccataratasoi boolean, rbecpterigionod boolean, rbecpterigionoi boolean, rbecpingueculaod boolean, rbecpingueculaoi boolean, rbecclalacionod boolean, rbecclalacionoi boolean, rbecotrosod boolean, rbecotrosoi boolean, txtechallazgos text, rbfonormalod boolean, rbfonormaloi boolean, rbfoanormalod boolean, rbfoanormaloi boolean, txtfohallazgos text, txtpiood text, txtpiooi text, txtpiona text, rbco_si boolean, rbco_no boolean, rbco_cerca boolean, rbco_lejos boolean, chkntcc boolean, chkntcl boolean, txtcercasincorregirod text, txtcercasincorregiroi text, txtlejossincorregirod text, txtlejossincorregiroi text, txtcercacorregidaod text, txtcercacorregidaoi text, txtlejoscorregidaod text, txtlejoscorregidaoi text, txtcercaagujerood text, txtcercaagujerooi text, txtlejosagujerood text, txtlejosagujerooi text, txtbinocularsincorregir text, txtbinocularcorregida text, rbtecishihara_normal boolean, rbtecishihara_anormal boolean, rbtecishihara_nc boolean, rbteccoleres_normal boolean, rbteccoleres_anormal boolean, rbteccoleres_nc boolean, txttecestereopsia text, rbtecestereopsia_normal boolean, rbtecestereopsia_anormal boolean, rbtecestereopsia_nc boolean, chkrefraccionaplica boolean, chkrefraccionnoaplica boolean, txtlejosodsf text, txtlejosodcil text, txtlejosodeje text, txtlejosoisf text, txtlejosoicil text, txtlejosoieje text, txtlejosoddip text, txtcercaodsf text, txtcercaodcil text, txtcercaodeje text, txtcercaoisf text, txtcercaoicil text, txtcercaoieje text, txtcercaoddip text, txtavconrefraccionlejosod text, txtavconrefraccionlejosoi text, txtavconrefraccioncercaod text, txtavconrefraccioncercaoi text, txtdiagnostico text, chkininguna boolean, chki2 boolean, chki3 boolean, chki4_cerca boolean, chki4_lejos boolean, chki5 boolean, chki6 boolean, chki7 boolean, chkr1 boolean, chkr2_lejos boolean, chkr2_cerca boolean, chkr3 boolean, chkr4 boolean, txtrp text, color integer, sede_descripcion text, dir_sede4 text, email_sede4 text, tel_sede4 text, cel_sede4 text, dir_sede3 text, email_sede3 text, tel_sede3 text, dir_sede2 text, email_sede2 text, tel_sede2 text, cel_sede2 text, dir_sede1 text, email_sede1 text, tel_sede1 text,
txt_parpa_anex text,
txt_corneas text,
txt_otros_hallaz text,
txt_conjuntivas text,
txt_cristalino text,
txt_ant_pers_imp text,
txt_fam_imp text
  ) AS
$BODY$
BEGIN
  RETURN QUERY
  SELECT 
    dp.nombres_pa,
    dp.apellidos_pa,
    CAST(obtener_edad(dp.fecha_nacimiento_pa, current_date) AS TEXT),

    o.n_orden,
    noo.cod_pa,
    dp.fecha_nacimiento_pa,
    noo.razon_empresa,
    noo.razon_contrata,
    noo.nom_examen,
    --dp.lugar_nac_pa,
    --dp.cel_pa,
    dp.sexo_pa,
    --dp.direccion_pa ||'-'|| dp.distrito_pa ||'-'|| dp.provincia_pa ||'-'|| dp.departamento_pa,
    --u.nombre_user||' '||u.apellido_user,
    o.cod_of,
    o.fecha_of,
    o.rbecptosisod,
    o.rbecptosisoi,
    o.rbecestrabismood,
    o.rbecestrabismooi,
    o.rbecconjuntivitisod,
    o.rbecconjuntivitisoi,
    o.rbeccataratasod,
    o.rbeccataratasoi,
    o.rbecpterigionod,
    o.rbecpterigionoi,
    o.rbecpingueculaod,
    o.rbecpingueculaoi,
    o.rbecclalacionod,
    o.rbecclalacionoi,
    o.rbecotrosod,
    o.rbecotrosoi,
    o.txtechallazgos,
    o.rbfonormalod,
    o.rbfonormaloi,
    o.rbfoanormalod,
    o.rbfoanormaloi,
    o.txtfohallazgos,
    o.txtpiood,
    o.txtpiooi,
    o.txtpiona,
    o.rbco_si,
    o.rbco_no,
    o.rbco_cerca,
    o.rbco_lejos,
    o.chkntcc,
    o.chkntcl,
    o.txtcercasincorregirod,
    o.txtcercasincorregiroi,
    o.txtlejossincorregirod,
    o.txtlejossincorregiroi,
    o.txtcercacorregidaod,
    o.txtcercacorregidaoi,
    o.txtlejoscorregidaod,
    o.txtlejoscorregidaoi,
    o.txtcercaagujerood,
    o.txtcercaagujerooi,
    o.txtlejosagujerood,
    o.txtlejosagujerooi,
    o.txtbinocularsincorregir,
    o.txtbinocularcorregida,
    o.rbtecishihara_normal,
    o.rbtecishihara_anormal,
    o.rbtecishihara_nc,
    o.rbteccoleres_normal,
    o.rbteccoleres_anormal,
    o.rbteccoleres_nc,
    o.txttecestereopsia,
    o.rbtecestereopsia_normal,
    o.rbtecestereopsia_anormal,
    o.rbtecestereopsia_nc,
    o.chkrefraccionaplica,
    o.chkrefraccionnoaplica,
    o.txtlejosodsf,
    o.txtlejosodcil,
    o.txtlejosodeje,
    o.txtlejosoisf,
    o.txtlejosoicil,
    o.txtlejosoieje,
    o.txtlejosoddip,
    o.txtcercaodsf,
    o.txtcercaodcil,
    o.txtcercaodeje,
    o.txtcercaoisf,
    o.txtcercaoicil,
    o.txtcercaoieje,
    o.txtcercaoddip,
    o.txtavconrefraccionlejosod,
    o.txtavconrefraccionlejosoi,
    o.txtavconrefraccioncercaod,
    o.txtavconrefraccioncercaoi,
    o.txtdiagnostico,
    o.chkininguna,
    o.chki2,
    o.chki3,
    o.chki4_cerca,
    o.chki4_lejos,
    o.chki5,
    o.chki6,
    o.chki7,
    o.chkr1,
    o.chkr2_lejos,
    o.chkr2_cerca,
    o.chkr3,
    o.chkr4,
    o.txtrp,


    noo.color,
    CAST(sm.descripcion AS TEXT),

    (SELECT direccion FROM sede WHERE cod_sede = 4),
    (SELECT email FROM sede WHERE cod_sede = 4),
    (SELECT telefono FROM sede WHERE cod_sede = 4),
    (SELECT celular FROM sede WHERE cod_sede = 4),

    (SELECT direccion FROM sede WHERE cod_sede = 3),
    (SELECT email FROM sede WHERE cod_sede = 3),
    (SELECT telefono FROM sede WHERE cod_sede = 3),

    (SELECT direccion FROM sede WHERE cod_sede = 2),
    (SELECT email FROM sede WHERE cod_sede = 2),
    (SELECT telefono FROM sede WHERE cod_sede = 2),
    (SELECT celular FROM sede WHERE cod_sede = 2),

    (SELECT direccion FROM sede WHERE cod_sede = 1),
    (SELECT email FROM sede WHERE cod_sede = 1),
    (SELECT telefono FROM sede WHERE cod_sede = 1),
    o.txt_parpa_anex,
    o.txt_corneas,
    o.txt_otros_hallaz,
    o.txt_conjuntivas,
    o.txt_cristalino,
    o.txt_ant_pers_imp,
    o.txt_fam_imp

  FROM datos_paciente dp
  INNER JOIN n_orden_ocupacional noo ON noo.cod_pa = dp.cod_pa
  INNER JOIN oftalmologia2021 o ON o.n_orden = noo.n_orden
  INNER JOIN sede_multisucursal sm ON noo.cod_sede = sm.id
  --INNER JOIN usuarios u ON LOWER(u.usuario_user) = LOWER(hoi.user_registro)
  WHERE noo.n_orden = p_norden;
END;
$BODY$
  LANGUAGE plpgsql
